version: "3.8"
services:
  backend:
    build: .
    env_file: ../.env
    depends_on:
      - mongodb
      - rabbitmq
      - redis
    # ports: ["8000:8000"] # if you expose an API server

  mongodb:
    image: mongo:5
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports: ["15672:15672", "5672:5672"]

  redis:
    image: redis:7
    restart: always
